### ISSUE TITLE
Seems to cause a 500 error when loading

### ISSUE THREAD

**Issue by mikebronner** [amitdar/Z-Ray-Online-Editor#1]
I haven't been able to trace down exactly what the error is, but if I have the plugin enabled, it always causes a 500 error, even though the page loads. Removing the plugin from ZendServer also gets rid of the 500 error.

**Comment by amitdar** [comment]
Can you be a little more specific about the OS, php version, Zend Server version and the application you are trying to load ?

**Comment by mikebronner** [comment]
Closing this as I am no longer using Z-Ray and am unable to follow up on this.
